In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

/home/vinoth/Apps/anaconda3/envs/stanford20/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

1.3453578


In [18]:
x = tf.random_uniform([], minval=-1, maxval=1)
y = tf.random_uniform([], minval=-1, maxval=1)

out = tf.case({ tf.greater(x, y): lambda: x + y, tf.less(x, y) : lambda: x- y },  default=lambda: tf.constant(0.), exclusive=True)

print(sess.run(out))

0.6141422


In [21]:
x = tf.constant([[0, -2, 0], [0, 1, 2]])
y = tf.zeros_like(x)

out = tf.equal(x, y)

print(sess.run(out))

[[ True False  True]
 [ True False False]]


In [24]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858])

id_greater_than_30 = tf.where(tf.greater(x, 30))
elem_greater_than_30 = tf.gather(x, id_greater_than_30)

print(sess.run(id_greater_than_30))
print(sess.run(elem_greater_than_30))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [27]:
x = tf.range(1,7)

diag = tf.diag(x)

print(sess.run(x))
print(sess.run(diag))

[1 2 3 4 5 6]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [34]:
mat = tf.random_poisson(2., [10, 10])
det = tf.matrix_determinant(mat)

print(sess.run(mat))
print(sess.run(det))

[[2. 0. 1. 2. 1. 1. 4. 3. 1. 7.]
 [0. 0. 1. 2. 3. 2. 2. 4. 4. 3.]
 [1. 3. 0. 2. 2. 2. 4. 1. 4. 2.]
 [2. 4. 1. 3. 4. 1. 2. 0. 1. 2.]
 [2. 2. 5. 0. 2. 4. 1. 1. 2. 2.]
 [1. 3. 1. 3. 2. 1. 3. 2. 4. 1.]
 [4. 1. 3. 0. 2. 4. 4. 0. 3. 3.]
 [0. 3. 3. 3. 2. 1. 3. 1. 0. 3.]
 [1. 3. 2. 0. 3. 2. 1. 0. 2. 2.]
 [5. 2. 2. 3. 1. 2. 2. 0. 4. 3.]]
-23864.01


In [38]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y,idx = tf.unique(x)

print(sess.run(y))

[ 5  2  3 10  6  4  1  0  9]


In [ ]:
x = tf.random_uniform([300])
y = tf.random_uniform([300])

tf.cond(tf.less(tf.reduce_mean(tf.subtract(x, y)), 0), lambda: )